{% set name = "fastnanquantile" %}
{% set version = "0.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d0059370a3e00f706531ed2f390433ea3d0d3dadc31574fd2c2cfde440ee326

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - numba
    - numpy
    - python >=3.8

test:
  imports:
    - fastnanquantile
  commands:
    - pip check
  requires:
    - pip

about:
  home: "https://github.com/lbferreira/fastnanquantile"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A package for fast nanquantile calculation"
  doc_url: https://github.com/lbferreira/fastnanquantile
  dev_url: https://github.com/lbferreira/fastnanquantile

extra:
  recipe-maintainers:
    - lbferreira
